---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-nfsshare
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: awx-projects-volume
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.69.58.202
    path: /awx_project

