---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-volume
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-postgres-volume
  nfs:
    server: 10.69.58.202
    path: /awx_project

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: awx-projects-volume
  nfs:
    server: 10.69.58.202
    path: /awx_project
