---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: awx-projects-claim
  namespace: awx 
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: awx-projects-volume
  resources:
    requests:
      storage: 20Gi
