---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: gold